### ISSUE TITLE
Sometimes no notifications for new received SMS messages

### ISSUE THREAD

**Issue by jimbobcraig** [FossifyOrg/Messages#159]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Messages/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.1

### Affected Android/Custom ROM version

Android 12

### Affected device model

Nokia G22

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

Receive an SMS from and external number (contact or non)

### Expected behavior

Receive a notification when a new message arrives.

### Actual behavior

Sometimes there is a notification, sometimes there is not. I can open the app manually and then the message list will show one conversation in bold (although in the list view the new message is not previewed) When I open the conversation then the new message appears at the bottom.

There seems to be no corelation between do-not-disturb / silent / vibrate global settings.

It appears random at the moment and has been an issue since installing. This wasn't a problem when the app was "simple mobile tools" AND before the Android 12 update but I can't pinpoint exactly when it started to happen. It's intermittant. Doesn't seem to differentiate between contacts or non-contacts. There are no per-contact custom notifications set. I have tried a "reset to defaults" of all phone notifications, but the behaviour persists.

**Comment by ulfi** [comment]
Same at my Gigaset GX6.
I reinstalled 1.0.1(NeoStore shows installed by F-droid and IzzyOnDroid)
I enabled all rights as well marked it as not stopped if it runs in background.

**Comment by WebworkrNet** [comment]
**Device**: Samsung Galaxy A13 5G (SM-A136B/DSN)
**Operating System**: Android 14, One UI-Version 6.1
**Fossify Messages**: Version 1.0.1
**Installed by** F-Droid

**Comment by Jawzper** [comment]
Same problem on my device. 

Device: Pixel 7 
OS: Android 13
Fossify Message: Version 1.0.1
Installed by: Play store

I have gone through my settings carefully to confirm the app should not be getting suspended somehow. Background data is enabled, pausing app if unused is disabled, data access and battery usage are unrestricted, and it's set as the default messaging app. And yet I've apparently been missing messages since yesterday, only to receive them all at once when I opened the app today. 

This app is unusable and dead to me until this is fixed - a messaging app that doesn't reliably receive messages is nothing but a source of stress. Some SMS messages are IMPORTANT. This has really ruined my day...

**Comment by jackthebean** [comment]
I have had this problem for months (both with Simple version and this Fossify version).  
Using 
Android 10, 
Honor View 20, 
Fossify Message 1.0.1 and 
installed from F-Droid.

and again problems are intermittent.  Mostly notification appears in proper place, sometimes just a dot on the app icon and sometimes nothing at all and don't see message until I open app for something else.

**Comment by rafael-alcantara** [comment]
Same here. Notifications are enabled but they don't always are received.
- Android 9
- Messages 1.1.5 installed fron f-droid

**Comment by vinceingithub** [comment]
I'm having this issue too, though I've noticed it only seems to be for certain senders for me. OTP messages specifically seem to get ignored the most.

**Comment by EchedelleLR** [comment]
Aside of this, even opening the app does not work and messages are lost.

Sometimes I have to keep the app opened in foreground and press again the options to resend SMS from other apps (mostly verification purposes) for those to be received.

I already did the following as @Jawzper:

> I have gone through my settings carefully to confirm the app should not be getting suspended somehow. Background data is enabled, pausing app if unused is disabled, data access and battery usage are unrestricted, and it's set as the default messaging app

**Comment by naveensingh** [comment]
@jimbobcraig @ulfi @Jawzper @rafael-alcantara @vinceingithub @EchedelleLR 

I have some questions for everyone facing this issue:

- How many contacts do you have?
- How many conversations/chats do you have?
- Do you have **Block messages from unknown numbers** enabled?

**Comment by jackthebean** [comment]
835 contacts
About 330 chats
No to block messages from unknown numbers but 6 unknown listed

Thanks,

**Comment by EchedelleLR** [comment]
* Contacts: more than 200
* Conversations: 12
* I dont block unknown numbers, this would affect me in bank notifications

**Comment by WebworkrNet** [comment]
> SMS/MMS delivery is handled by the system. There's no need for push messages.
> 
> The app's role is to write these messages to the database and notify the user (the glitchy part). This was reported multiple times in SMT but I was never able to reproduce it.

@naveensingh 
What is meant by “the glitchy part”?
And what does the abbreviation “SMT” stand for in this context?

Thanks

**Comment by naveensingh** [comment]
> What is meant by “the glitchy part”?

I mean the app component that seems to be failing here (notifying the user).

> And what does the abbreviation “SMT” stand for in this context?

Fossify apps are forked from SimpleMobileTools, which is sometimes abbreviated as SMT ([click for additional context](https://github.com/SimpleMobileTools/General-Discussion/issues/241)).

**Comment by naveensingh** [comment]
It _should_ be fixed in the next update.

**Comment by rasmussehlin** [comment]
I'm currently experiencing this issue. Not getting any notifications. The conversations with new messages are rendered in bold though.
- Samsung Galaxy S23
- Android 16.0
- Fossify Messages 1.7.0 (installed from play store)
- Contacts: 441
- Conversations: 462
- Block messages from unknown numbers: disabled

I've reinstalled the app, still the same issue.

**Comment by naveensingh** [comment]
The new version isn't out yet. You can install a pre-release build from [here](https://github.com/FossifyOrg/Messages/pull/643#issuecomment-3678633051).

**Comment by WebworkrNet** [comment]
v1.8.0-nightly-d53ebfb

Initial observations indicate that the problem has not been (completely) resolved.
I'll keep an eye on this to see if it pans out.
